steps:
- name: 'gcr.io/cloud-builders/java/mvn'
  args: ['clean']
- name: 'gcr.io/cloud-builders/java/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/java/mvn'
  args: ['assembly:single']
- name: 'gcr.io/cloud-builders/java/mvn'
  args: ['docker:build']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '--tag=gcr.io/$PROJECT_ID/kafdrop', '.']
images: ['kafdrop']